name: Bug Report
description: Something isn't working right
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - cassidyjames
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! **Please provide enough detail for me to reproduce the issue** if possible; otherwise, it's a lot harder to debug and fix reported issues!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: And what did you expect to happen?
      placeholder: "I clicked… and saw…"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      description: Copy from Clairvoyant by going to About, then selecting the version nunber
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What OS are you running the app on?
      placeholder: e.g. Ubuntu, Fedora Silverblue, GNOME OS…
  - type: dropdown
    id: packaging
    attributes:
      label: Packaging/distribution
      description: Where did you get Clairvoyant?
      options:
        - Compiled from source
        - Flatpak (Flathub)
        - Snap
        - Other
  - type: input
    id: packaging-other
    attributes:
      label: Specify “other” packaging
      description: If you chose “other” above, name it here
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [GNOME Code of Conduct](https://wiki.gnome.org/Foundation/CodeOfConduct)
      options:
        - label: I agree to follow the GNOME Code of Conduct
          required: true
